import images from "../components/importImages";
export const Job = [
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },
    {
        id: 1,
        image: images["bg4.jpg"],
        title: 'Graphic Designer ',
        amount: 20,
        description : "Thiết kế đồ họa, phân tích hình ảnh, vẽ minh họa, sử dụng photoshop",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
    },

]