import images from "../components/importImages";
export const Job = [
    {
        id: 0,
        image: images["graphic.jpg"],
        title: 'GRAPHIC DESIGNER',
        field: 'Thiết kế',
        description : "Tạo ra thiết kế đồ họa sáng tạo và chuyên nghiệp, từ hình ảnh, biểu đồ, đồ hoạ và logo, để truyền tải thông điệp và thương hiệu một cách hấp dẫn và thẩm mỹ.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/Graphic-Designer",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 1,
        image: images["front end.jpg"],
        title: 'FRONT-END DEVELOPER',
        field: 'Lập trình web',
        description : "Xây dựng giao diện người dùng hấp dẫn và tương tác trên trang web hoặc ứng dụng, sử dụng các ngôn ngữ và công cụ như HTML, CSS và JavaScript.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/FE-Developer",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 2,
        image: images["back end.jpg"],
        title: 'BACK-END DEVELOPER',
        field: 'Lập trình web',
        description : "Xây dựng và quản lý phần server, bao gồm xử lý dữ liệu, tương tác với cơ sở dữ liệu, và đảm bảo hệ thống hoạt động mượt mà và bảo mật.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/BE-Developer",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 3,
        image: images["content.jpg"],
        title: 'CONTENT CREATOR',
        field: 'Truyền thông',
        description : "Tạo ra nội dung đa dạng và sáng tạo, bao gồm viết bài và quản lý nội dung, nhằm góp phần xây dựng thương hiệu và tương tác với khán giả",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/content-creator",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 4,
        image: images["photograph.jpg"],
        title: 'PHOTOGRAPHER',
        field: 'Dựng phim',
        description : "Sử dụng kỹ thuật và cảm nhận nghệ thuật để chụp ảnh chất lượng cao từ các sự kiện, chân dung, cảnh đẹp đến sản phẩm và quảng cáo.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/photograph",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 5,
        image: images["camera man.jpg"],
        title: 'CAMERAMAN',
        field: 'Dựng phim',
        description : "Quay phim và ghi lại hình ảnh chuyên nghiệp đảm bảo chất lượng để tạo ra các tác phẩm trực tiếp, phim ngắn, quảng cáo hoặc sản phẩm truyền thông.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/cameraman",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 6,
        image: images["actor.jpg"],
        title: 'ACTOR / ACTRESS',
        field: 'Điện ảnh',
        description : "Thể hiện vai diễn và biểu đạt cảm xúc qua diễn xuất trên sân khấu hoặc trên màn ảnh, tham gia vào các dự án nghệ thuật của CLB.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/actor",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 7,
        image: images["director.jpg"],
        title: 'FILM DIRECTOR',
        field: 'Dựng phim',
        description : "Đảm nhiệm vai trò chỉ đạo, lãnh đạo quá trình sản xuất phim, từ viết kịch bản, đạo diễn diễn viên, chỉ đạo quay phim cho đến dựng phim.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/director",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 8,
        image: images["artist.jpg"],
        title: 'ARTIST',
        field: 'Thiêt kế',
        description : "Sáng tạo và thể hiện tài năng nghệ thuật thông qua việc vẽ, tạo hình để tạo ra các tác phẩm nghệ thuật độc đáo và thẩm mỹ.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/artist",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 9,
        image: images["video editor.jpg"],
        title: 'VIDEO EDITOR',
        field: 'Thiêt kế',
        description : "Chỉnh sửa và biên tập các đoạn video, ghép cắt, tạo hiệu ứng hình ảnh và âm thanh, để tạo ra các tác phẩm video chất lượng cao và hấp dẫn.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/video-editor",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 10,
        image: images["art director.jpg"],
        title: 'ART DIRECTOR',
        field: 'Điện ảnh',
        description : "Thiết kế và sắp xếp bối cảnh, trang phục và makeup cho các hoạt động nghệ thuật, sự kiện hoặc dự án của CLB.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/art-director",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
    {
        id: 11,
        image: images["advisor.jpg"],
        title: 'SPECIALIZED ADVISOR',
        field: 'Tùy chọn',
        description : "Cung cấp kiến ​​thức chuyên môn, kỹ năng và hướng dẫn cho thành viên CLB trong lĩnh vực cụ thể giúp cải thiện và phát triển tài năng và kỹ năng của họ.",
        require: "Có đam mê và trách nhiệm với công việc, không lười biếng, có chí cầu tiến, tích cực xây dựng CLB",
        link: "/ndc-multimedia/advisor",
        description_detail: "As the Design Team Leader, you will own the entire product design and be responsible for both the look and feel of an online recruitment platform that will be used by hundreds of thousands of users & corporate customers. As our first Design Team leader hire, you will play a foundational role in defining and building out the Product Design function and team.",
        skill: ["Working experience delivering multiple projects with cross-disciplined teams","Proficient in Figma, Sketch or similar design tools to develop wireframes and prototypes","Knowledge of technical constraints with HTML5, CSS3","Working experience designing tech products from the scratch"],
        pictures: [images['designing.jpg'],images['designing.png'],images['designteam.png']],
    },
]