import images from '../components/importImages';
const exampleDB = [
    {
        id: 1,
        name: "name",
        avatar: "imagefile",
        address: "Class - school",
        roles: "role",
        facebook: "https://www.facebook.com/rinncuto6mui",
        discord: "http://discord.gg/eVgvc3e994",
        twitter: "https://twitter.com/rinncuto",
    },
]
export const memberDB = [
    {
        name: "Nguyễn Lý Tính",
        avatar: images['Tinh.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["CEO & Co-Founder"],
        description:"Proficient in After Effects and Premiere & administrator of Discord Prison.",
        facebook: "https://www.facebook.com/rinncuto6mui",
        discord: "http://discord.gg/eVgvc3e994",
        twitter: "https://twitter.com/rinncuto",
    },
    {
        name: "Phạm Ngọc Gia Bảo",
        avatar: images['Bao.jpg'],
        address: ["10T - @NguyenDinhChieu"],
        roles: ["Web Developer"],
        description:"Experienced in ReactJS, Java, and Figma. Enjoys playing Minecraft.",
        facebook: "https://www.facebook.com/kyrA67",
        github: "https://github.com/baoozuma",
        instagram: "https://www.instagram.com/idealismgb/",
    },
    {
        id: 8,
        name: "Ngô Trần Thành Bình",
        avatar: images['tbinh.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Cameraman & Director"],
        description: "Perfectionist lover, never forgets to capture every precious frame.",
        facebook: "https://www.facebook.com/htanh.bee",
        youtube: "none",
        tiktok: "none",
    },
    {
        name: "Đoàn Thị Ngọc Thúy",
        avatar: images['ngthuy.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Photographer"],
        description:"Possesses a keen eye for composition, lighting, and framing.",
        facebook: "https://www.facebook.com/profile.php?id=100083080183088",
        instagram: "none",
        tiktok: "none",
    },
    {
        name: "Lê Phước Sang",
        avatar: images['david.png'],
        address: "12V - @NguyenDinhChieu",
        roles: ["Writer & Marketing Professional"],
        description:"Passionate about romanticism, the mastermind of the club.",
        facebook: "https://www.facebook.com/lps2019.2020.meme",
        youtube: "none",
        tiktok: "none",
    },
    {
        name: "Lê Trường Khải",
        avatar: images['khai.jpg'],
        address: "10T - @NguyenDinhChieu",
        roles: ["Data Analyst & Sponsor"],
        description: "The passionate tech enthusiast, love math.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },

    {
        name: "Huỳnh Tuấn Vũ",
        avatar: images['tvu.jpg'],
        address: "10L - @NguyenDinhChieu",
        roles: ["Graphic Designer"],
        description: "Always wears a smile and enjoys helping others.",
        facebook: "https://www.facebook.com/profile.php?id=100076616990748",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 7,
        name: "Cao Bích Tuyền",
        avatar: images['tuyen.jpg'],
        address: "10T - @NguyenDinhChieu",
        roles: ["Actress"],
        description: "The center of the party, having participated in various roles.",
        facebook: "https://www.facebook.com/profile.php?id=100050846086694",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 10,
        name: "Võ Thị Thảo Quyên",
        avatar: images['tquyen.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Writer & Director"],
        description: "The film's visionary writer and main director in various projects.",
        facebook: "https://www.facebook.com/profile.php?id=100023993326517",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 11,
        name: "Trần Nguyễn Khánh",
        avatar: images["khanh.jpg"],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Model & Actor"],
        description: "Badass handsome guy, ideal man figure",
        facebook: "https://www.facebook.com/profile.php?id=100071797683036",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 12,
        name: "Đoàn Thị Thu Ngân",
        avatar: images["ngandoan.jpg"],
        address: "10A2 - @NguyenDinhChieu",
        roles: ["Actor & Director"],
        description: "Dreamy girl, passionately dedicating herself to the world of cinema.",
        facebook: "https://www.facebook.com/profile.php?id=100078707321008",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 13,
        name: "Bùi Nguyễn Trúc An",
        avatar: images["rush.jpg"],
        address: "10S - @NguyenDinhChieu",
        roles: ["Photographer & Director"],
        description: "Ambitious, inventive, and groundbreaking.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 14,
        name: "Nguyễn Đình Anh Quân",
        avatar: images["henri.png"],
        address: "10T - @NguyenDinhChieu",
        roles: ["Business Analyst"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 15,
        name: "Erin Reese",
        avatar: images["erin.png"],
        address: "10AV - @NguyenDinhChieu",
        roles: ["Writer & Editor"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 16,
        name: "Alexandra Wang",
        avatar: images["alexandra.jpg"],
        address: "123 Main Street, New York, NY",
        roles: ["Software Developer"],
        description: "Backend developer with experience in Python, Node.js, and SQL.",
        linkedin: "https://www.linkedin.com/in/alexandrawang/",
        twitter: "https://twitter.com/alex_wang",
        github: "https://github.com/alexwang",
        facebook: "https://www.alexwang.dev/"
    },
    {
        id: 17,
        name: "Samantha Lee",
        avatar: images["samantha.jpg"],
        address: "500 Elm Street, Chicago, IL",
        roles: ["Graphic Designer"],
        description: "Specializes in branding and packaging design with Adobe.",
        instagram: "https://www.instagram.com/samanthalee.design/",
        twitter: "https://www.behance.net/samanthalee_design",
        github: "https://dribbble.com/samanthalee_design",
        website: "https://www.samanthaleedesign.com/"
    },
    
    {
        id: 18,
        name: "David Kim",
        avatar: images["david.png"],
        address: "321 Broadway, San Francisco, CA",
        roles: ["Product Manager"],
        description: "Experienced in leading teams to deliver software products.",
        facebook: "https://www.linkedin.com/in/davidkim/",
        twitter: "https://twitter.com/davidkim",
        youtube: "https://davidkim.medium.com/",
        website: "https://www.davidkim.pm/"
    },
    
    {
        id: 19,
        name: "Emily Chen",
        avatar: images["emily.jpg"],
        address: "789 Oak Street, Seattle, WA",
        roles: ["Marketing Manager"],
        description: "Experienced in digital marketing and social media strategy.",
        youtube: "https://www.linkedin.com/in/emily-chen/",
        twitter: "https://twitter.com/emilychen",
        instagram: "https://www.instagram.com/emilychen.marketing/",
        website: "https://www.emilychen.marketing/"
    },
    
    {
        id: 20,
        name: "Michael Rodriguez",
        avatar: images["michael.jpg"],
        address: "555 Pine Street, Los Angeles, CA",
        roles: ["Sales Manager"],
        description: "Experienced in managing and developing sales.",
        facebook: "https://www.linkedin.com/in/michael-rodriguez/",
        twitter: "https://twitter.com/michaelrodriguez",
        github: "https://www.michaelrodriguezsales.com/"
    },
    
    {
        id: 21,
        name: "Avery Nguyen",
        avatar: images["avery.jpg"],
        address: "456 Oak Street, Austin, TX",
        roles: ["UX Designer"],
        description: "Specializes in user research and interface design.",
        linkedin: "https://www.linkedin.com/in/avery-nguyen/",
        facebook: "https://dribbble.com/averynguyen",
        instagram: "https://www.behance.net/averynguyen",
        github: "https://www.averynguyen.design/"
    },
    
    {
        id: 22,
        name: "Jordan Baker",
        avatar: images["jordan.jpg"],
        address: "789 Main Street, Boston, MA",
        roles: ["Data Analyst"],
        description: "Experienced in statistical analysis and data visualization.",
        facebook: "https://dribbble.com/averynguyen",
        twitter: "https://www.behance.net/averynguyen",
        github: "https://www.averynguyen.design/"
    }
]
