import images from '../components/importImages';
const exampleDB = [
    {
        id: 1,
        name: "name",
        avatar: "imagefile",
        address: "Class - school",
        roles: "role",
        facebook: "https://www.facebook.com/rinncuto6mui",
        discord: "http://discord.gg/eVgvc3e994",
        twitter: "https://twitter.com/rinncuto",
    },
]
export const memberDB = [
    {
        id: 1,
        name: "Nguyễn Lý Tính",
        avatar: images['Tinh.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["CEO & Co-Founder"],
        description:"Passionate TypeScript enthusiast working extensively with Vue SPA and pug.",
        facebook: "https://www.facebook.com/rinncuto6mui",
        discord: "http://discord.gg/eVgvc3e994",
        twitter: "https://twitter.com/rinncuto",
    },
    {
        id: 2,
        name: "Phạm Ngọc Gia Bảo",
        avatar: images['Bao.jpg'],
        address: ["10T - @NguyenDinhChieu"],
        roles: ["Fullstack Developer"],
        description:"Independent open source developer, creator of Vue.js and Vite.",
        facebook: "https://www.facebook.com/kyrA67",
        github: "https://github.com/baoozuma",
        instagram: "https://www.instagram.com/idealismgb/",
    },
    {
        id: 3,
        name: "Nguyễn Quốc Thái",
        avatar: images['qthai.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Backend Developer"],
        description:"Dabbling in social ecommerce, meta frameworks, and board games",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 4,
        name: "Phan Thành Nguyên",
        avatar: images['nguyen.jpg'],
        address: "10L - @NguyenDinhChieu",
        roles: ["Backend Developer"],
        description:"Passionate by tooling around TypeScript and React.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Lê Trường Khải",
        avatar: images['khai.jpg'],
        address: "10T - @NguyenDinhChieu",
        roles: ["Data Analyst & Economist"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },

    {
        id: 6,
        name: "Huỳnh Tuấn Vũ",
        avatar: images['tvu.jpg'],
        address: "10L - @NguyenDinhChieu",
        roles: ["Business Analyst"],
        description: "Dabbling in social ecommerce, meta frameworks, and board games",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 7,
        name: "Cao Bích Tuyền",
        avatar: images['tuyen.jpg'],
        address: "10T - @NguyenDinhChieu",
        roles: ["Actress"],
        description: "Passionate by tooling around TypeScript and React.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 8,
        name: "Trần Ngô Thành Bình",
        avatar: images['tbinh.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Cameraman"],
        description: "Web Developer. Vue & Vite team member",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 9,
        name: "Phạm Tuấn Vũ",
        avatar: images['pvu.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Graphic Designer"],
        description: "Vite team member. Call me sapphi or green or midori ;)",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 10,
        name: "Võ Thị Thảo Quyên",
        avatar: images['tquyen.jpg'],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Writer & Director"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 11,
        name: "Taron Marijana",
        avatar: images["taron.jpg"],
        address: "10V - @NguyenDinhChieu",
        roles: ["Writer & Marketer"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 12,
        name: "Ewan Arias",
        avatar: images["ewan.jpg"],
        address: "10TH - @NguyenDinhChieu",
        roles: ["Editor & UI Designer"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 13,
        name: "Zaynah Rush",
        avatar: images["rush.jpg"],
        address: "10H - @NguyenDinhChieu",
        roles: ["Content Creator & Actress"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 14,
        name: "Henri Mcconnell",
        avatar: images["henri.png"],
        address: "10T - @NguyenDinhChieu",
        roles: ["Business Analyst"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 15,
        name: "Erin Reese",
        avatar: images["erin.png"],
        address: "10AV - @NguyenDinhChieu",
        roles: ["Writer & Editor"],
        description: "Astro core residency. Svelte and Vite core team member.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 16,
        name: "Alexandra Wang",
        avatar: images["alexandra.jpg"],
        address: "123 Main Street, New York, NY",
        roles: ["Software Developer"],
        description: "Backend developer with experience in Python, Node.js, and SQL.",
        linkedin: "https://www.linkedin.com/in/alexandrawang/",
        twitter: "https://twitter.com/alex_wang",
        github: "https://github.com/alexwang",
        facebook: "https://www.alexwang.dev/"
    },
    {
        id: 17,
        name: "Samantha Lee",
        avatar: images["samantha.jpg"],
        address: "500 Elm Street, Chicago, IL",
        roles: ["Graphic Designer"],
        description: "Specializes in branding and packaging design with Adobe.",
        instagram: "https://www.instagram.com/samanthalee.design/",
        twitter: "https://www.behance.net/samanthalee_design",
        github: "https://dribbble.com/samanthalee_design",
        website: "https://www.samanthaleedesign.com/"
    },
    
    {
        id: 18,
        name: "David Kim",
        avatar: images["david.png"],
        address: "321 Broadway, San Francisco, CA",
        roles: ["Product Manager"],
        description: "Experienced in leading cross-functional teams to deliver innovative software products.",
        facebook: "https://www.linkedin.com/in/davidkim/",
        twitter: "https://twitter.com/davidkim",
        youtube: "https://davidkim.medium.com/",
        website: "https://www.davidkim.pm/"
    },
    
    {
        id: 19,
        name: "Emily Chen",
        avatar: images["emily.jpg"],
        address: "789 Oak Street, Seattle, WA",
        roles: ["Marketing Manager"],
        description: "Experienced in digital marketing and social media strategy.",
        youtube: "https://www.linkedin.com/in/emily-chen/",
        twitter: "https://twitter.com/emilychen",
        instagram: "https://www.instagram.com/emilychen.marketing/",
        website: "https://www.emilychen.marketing/"
    },
    
    {
        id: 20,
        name: "Michael Rodriguez",
        avatar: images["michael.jpg"],
        address: "555 Pine Street, Los Angeles, CA",
        roles: ["Sales Manager"],
        description: "Experienced in managing sales teams and developing sales strategies.",
        facebook: "https://www.linkedin.com/in/michael-rodriguez/",
        twitter: "https://twitter.com/michaelrodriguez",
        github: "https://www.michaelrodriguezsales.com/"
    },
    
    {
        id: 21,
        name: "Avery Nguyen",
        avatar: images["avery.jpg"],
        address: "456 Oak Street, Austin, TX",
        roles: ["UX Designer"],
        description: "Specializes in user research and interface design.",
        linkedin: "https://www.linkedin.com/in/avery-nguyen/",
        facebook: "https://dribbble.com/averynguyen",
        instagram: "https://www.behance.net/averynguyen",
        github: "https://www.averynguyen.design/"
    },
    
    {
        id: 22,
        name: "Jordan Baker",
        avatar: images["jordan.jpg"],
        address: "789 Main Street, Boston, MA",
        roles: ["Data Analyst"],
        description: "Experienced in statistical analysis and data visualization.",
        facebook: "https://dribbble.com/averynguyen",
        twitter: "https://www.behance.net/averynguyen",
        github: "https://www.averynguyen.design/"
    }
]
