import images from './components/importImages';

export const memberDB = [
    {
        id: 1,
        name: "Nguyễn Lý Tính",
        avatar: images['Tinh.jpg'],
        andress: "10TH - Nguyen Dinh Chieu",
        roles: ["CEO & Co-Founder"],
        facebook: "https://www.facebook.com/rinncuto6mui",
        discord: "http://discord.gg/eVgvc3e994",
        twitter: "https://twitter.com/rinncuto",
    },
    {
        id: 2,
        name: "Phạm Ngọc Gia Bảo",
        avatar: images['Bao.jpg'],
        andress: ["10T - Nguyen Dinh Chieu"],
        roles: ["Web Founder","Fullstack Developer"],
        facebook: "https://www.facebook.com/kyrA67",
        github: "https://github.com/baoozuma",
        instagram: "https://www.instagram.com/idealismgb/",
    },
    {
        id: 3,
        name: "Nguyễn Quốc Thái",
        avatar: images['qthai.jpg'],
        andress: "10TH - Nguyen Dinh Chieu",
        roles: ["Web Founder","Backend Developer"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 4,
        name: "Phan Thành Nguyên",
        avatar: images['nguyen.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Web Founder","Backend Developer"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Lê Trường Khải",
        avatar: images['khai.jpg'],
        andress: "10T - Nguyen Dinh Chieu",
        roles: ["Data Analyst & Economist"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },

    {
        id: 6,
        name: "Huỳnh Tuấn Vũ",
        avatar: images['tvu.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Business Analyst"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 7,
        name: "Cao Bích Tuyền",
        avatar: images['tuyen.jpg'],
        andress: "10T - Nguyen Dinh Chieu",
        roles: ["Actress","Master of Ceremonies"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 8,
        name: "Trần Ngô Thành Bình",
        avatar: images['tbinh.jpg'],
        andress: "10TH - Nguyen Dinh Chieu",
        roles: ["Cameraman"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 9,
        name: "Phạm Tuấn Vũ",
        avatar: images['pvu.jpg'],
        andress: "10TH - Nguyen Dinh Chieu",
        roles: ["Graphic Designer"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 10,
        name: "Võ Thị Thảo Quyên",
        avatar: images['tquyen.jpg'],
        andress: "10TH - Nguyen Dinh Chieu",
        roles: ["Writer & Director"],
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },




    
]