import images from './components/importImages';

export const memberDB = [
    {
        id: 1,
        name: "Nguyễn Lý Tính",
        avatar: images['Tinh.jpg'],
        andress: "10TH - Nguyen Dinh Chieu",
        roles: ["CEO & Co-Founder"],
        description: "Believe you can and you're halfway there.",
        facebook: "https://www.facebook.com/rinncuto6mui",
        discord: "http://discord.gg/eVgvc3e994",
        twitter: "https://twitter.com/rinncuto",
    },
    {
        id: 2,
        name: "Phạm Ngọc Gia Bảo",
        avatar: images['Bao.jpg'],
        andress: ["10T - Nguyen Dinh Chieu"],
        roles: ["Fullstack Developer","AI Engineer"],
        description: "CSS Grid is king of layout.",
        facebook: "https://www.facebook.com/kyrA67",
        github: "https://github.com/baoozuma",
        instagram: "https://www.instagram.com/idealismgb/",
    },
    {
        id: 3,
        name: "Lê Trường Khải",
        avatar: images['khai.jpg'],
        andress: "10T - Nguyen Dinh Chieu",
        roles: ["Data Analyst & Economist"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 4,
        name: "Phan Thành Nguyên",
        avatar: images['nguyen.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Backend Developer"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Phạm Tuấn Vũ",
        avatar: images['tvu.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Business Analyst"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Phạm Tuấn Vũ",
        avatar: images['tvu.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Business Analyst"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Phạm Tuấn Vũ",
        avatar: images['tvu.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Business Analyst"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Phạm Tuấn Vũ",
        avatar: images['tvu.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Business Analyst"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    {
        id: 5,
        name: "Phạm Tuấn Vũ",
        avatar: images['tvu.jpg'],
        andress: "10L - Nguyen Dinh Chieu",
        roles: ["Business Analyst"],
        description: "You don't have to be great to start, but you have to start to be great.",
        facebook: "https://www.facebook.com/profile.php?id=100064135344554",
        youtube: "none",
        tiktok: "none",
    },
    


    
]